apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-device-plugin-v4l2l
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: k8s-device-plugin-v4l2l
  template:
    metadata:
      labels:
        name: k8s-device-plugin-v4l2l
    spec:
      priorityClassName: system-node-critical
      containers:
      - image: matthiaspreu/k8s-device-plugin-v4l2loopback:latest
        name: k8s-device-plugin-v4l2l
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins